# Generated by Django 3.2 on 2021-04-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceclass',
            name='assign',
        ),
        migrations.AlterUniqueTogether(
            name='attendancetotal',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='attendancetotal',
            name='course',
        ),
        migrations.RemoveField(
            model_name='attendancetotal',
            name='student',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='section',
            new_name='batch',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='USN',
            new_name='PRN',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='AttendanceClass',
        ),
        migrations.DeleteModel(
            name='AttendanceTotal',
        ),
    ]
